### ISSUE TITLE
Category Model

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/shop-management#18]
# DOD
- [x] make migration based on #17 
- [x] handle fillable
- [x] handle relations with product
- [x] handle relations with the parent category
- [x] handle relation with children categories
- [x] make policy class
- [x] make sure if the category has a product or children should not be deleted ( should handle in policy + write unit test )

**Comment by mj999666** [comment]
@sdehgh Please do this.

- [x] Use `php artisan make:mode --option` ( option: make `Migration`, `Policy`, ... ) .Write me the used `stub`
- [x] Handle `fillable` or you can use `guarded`. Write me what you used. I prefer to use `guarded`

And I do these things

- [x]  handle relations
- [x] unit test
- [x] policy

**Comment by sdehgh** [comment]
#18 create model/Create migration/Create controller/create request
