### ISSUE TITLE
Telegram Notification

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/shop-management#47]
# story
as Admin, it should be able to make a telegram channel, add a bot to the management of the channel, and should get new products, updates, and discounts on the telegram page.

# technical 
- make a service to interact with Telegram ( we just want to send messages to telegram it doesn't need to implement telegram bot update )
- make an event to send telegram messages the message structure is :
- - photo 
- - title
- - description ( get from Product CRUD as `social_message` key) { you should update product crud and tests but do not store this social message on database }

# DOD 
- [x] telegram service with test 
- [x] it should be able to send telegram message to special channel with photo and description
- [x] update Product CRUD and add `social_message` key, if the key isset, you should to send notification to channel

# Resources : 
- https://www.youtube.com/playlist?list=PL6MpbG5qSD2CsCPBVmVikS_eTCjRDwvzB
- https://youtu.be/5aOIEf1yXdI
- https://core.telegram.org/bots/api
- https://www.youtube.com/watch?v=gj3oPpt-Xx0

**Comment by semjz** [comment]
I think the task will be done by the end of Saturday.
